# Use the base Python image
FROM python:3.9-slim

# Set work directory
WORKDIR /app

# Copy requirements first to optimize caching
COPY requirements.txt .

# Install pip and dependencies
RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy the rest of the code
COPY . .

# Expose port for the application
EXPOSE 8080

# Start the Flask application
CMD ["python", "app.py"]
